name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.User_Token }}
          user: MamadjavadAlizade
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tehran

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_skipped: ''
          plugin_languages_limit: 8

          plugin_stars: yes
          plugin_followup: yes
          plugin_lines: yes
          plugin_traffic: yes
