name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # هر روز ساعت ۰۰:۰۰ UTC اجرا می‌شود
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: mamadjavadalizade
          base: header, activity, community, repositories, metadata
